title: j1v37u2k3y's Blog
repository: j1v37u2k3y/j1v37u2k3y.github.io
author:
  name: Jive Turkey
  email: j1v37u2k3y@protonmail[.]com
description: > # this means to ignore newlines until "show_excerpts:"
  This is a blog dedicated to all the things that I am currently working on.

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--cut-->
paginate: 5

# Disqus comments
disqus:
  shortname:  j1v37u2k3y

# Google Analytics
google_analytics: G-NS39V4TDP8

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter:
      url: https://x.com/j1v37u2k3y
    github:
      url: https://github.com/j1v37u2k3y
# Build settings
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-toc

header_pages:
  - pages/about.md
  - pages/posts.md
  - pages/categories.md
  - pages/tags.md
  - pages/cheatsheet.md

category_page: /categories
tag_page: /tags
